#Первый вариант:
FROM java:8
COPY ./DataEngineer_ScalaPractice/lib ./app	
COPY ./DataEngineer_ScalaPractice/target/scala-2.13/dataengineer_scalapractice_2.13-0.1.0-SNAPSHOT.jar ./app
WORKDIR app
-----------------
Запуск:
docker run scala2 java -cp "./*" load.LoadStarter ...(params)
